"""empty message

Revision ID: 39dc3e9674b0
Revises: d4ebd51f9b1b
Create Date: 2016-12-20 15:24:50.136000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39dc3e9674b0'
down_revision = 'd4ebd51f9b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('follows', 'timsetamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('timsetamp', mysql.DATETIME(), nullable=True))
    op.drop_column('follows', 'timestamp')
    # ### end Alembic commands ###
