"""empty message

Revision ID: f05a5c970815
Revises: d416aa3d90e6
Create Date: 2016-12-16 16:23:52.425000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f05a5c970815'
down_revision = 'd416aa3d90e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
